### PR TITLE
Create API and send response as JSON

### PR DESCRIPTION
**Pull request by sumon766**
- Create model, migration and controllers for greeting messages
- Create seed data in the database seed
- Create API endpoints
- Setup and configure rails API to properly send json response through API

Link to frontend pull request: https://github.com/sumon766/hello-rr-frontend/pull/1

### CODE REVIEW

**Comment by KDlamini** [comment]
## Status: Invalid 🔴 

### Hi @sumon766  🙋‍♀️,  

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Code Review Request
 
You have submitted a project, that does not meet all requirements for a valid submission. Please consider these points before your project can be reviewed.

1. In the README file for the backend, there should be a link to the frontend repo.
1. In the README file for the fronted, there should be a link to the backend repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by sumon766** [comment]
@KDlamini Thanks for the review. I updated the links in the readme as you required.

**Comment by sumon766** [comment]
> @sumon766 would you add backend link on front pr as you did on backend side, the front mit license and also those links on both readme 

I am working on it.

**Comment by sumon766** [comment]
> @sumon766 would you add backend link on front pr as you did on backend side, the front mit license and also those links on both readme 

I already have added the links to frontend react and the backend API in the readme files. They are updated in the "Update readme commit". Please have a look.

**Review by binhussen — APPROVED** [review]
Hi @sumon766 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
- Setuped rails with React✔️
- Well Structured Code✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
